"""added uuid

Revision ID: 342fe2834dc0
Revises: ca21ecbd3138
Create Date: 2021-06-24 18:59:34.097564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '342fe2834dc0'
down_revision = 'ca21ecbd3138'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UUID',
    sa.Column('uuid', sa.String(length=255), nullable=False),
    sa.Column('nota_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UUID')
    # ### end Alembic commands ###
